name: Deploy Infrastructure

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  call-terraform-workflow:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

      # - name: Configurar credenciales de Git
      #   run: |

      #     echo "https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials
      #     git config --global credential.helper store

        uses: marcosfundacion/pipeline/.github/workflows/deploy.yml@main
        with:
          working-directory: './terraform'
          terraform-version: '1.3.0'
          aws-region: 'us-east-1'
          principal-role-arn: 'arn:aws:iam::754478843459:role/fsfb-arquitectura-despliegue-github'
          target-role-arn: 'arn:aws:iam::699631259047:role/fsfb-arquitectura-dev-role-despliegue'
          environment: 'dev'
          var-file-path: 'environments/dev/terraform.tfvars'
        secrets:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.personal_access_token }}