name: "Terraform Deployment"

on:
  push:
    branches:
      - dev
      - qa
      - prod
      - dr
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init:
    name: "Initialize Terraform"
    uses: marcosfundacion/pipeline/.github/workflows/init.yml@main
    with:
      aws_region: "us-east-1"
      terraform_version: "1.5.7"
      backend_s3_bucket: "terraform-backend-190018864982"
      backend_key_prefix: "terraform/state"
    secrets:
      OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
      TARGET_ROLE_ARN: ${{ secrets.TARGET_ROLE_ARN }}

