name: Sample Workflow

# Equivalente a la sección 'trigger' de Azure Pipelines
on:
  push:
    branches:
      - prod
      - qa
      - dev
      - dr
    paths-ignore:
      - '.github/workflows/sample-workflow.yml'

# Permiso para solicitar el token JWT para la autenticación OIDC
permissions:
  id-token: write
  contents: read


jobs:
  call-reusable-workflow:
    
    uses: marcosfundacion/pipeline/.github/workflows/iac_github_actions.yml@main
    with:
      principal-role-arn: 'arn:aws:iam::754478843459:role/fsfb-arquitectura-despliegue-github'
      target-role-arn: ${{ 
        github.ref_name == 'prod' && 'arn:aws:iam::699631259047:role/fsfb-arquitectura-prod-role-despliegue' ||
        github.ref_name == 'qa' && 'arn:aws:iam::699631259047:role/fsfb-arquitectura-qa-role-despliegue' ||
        github.ref_name == 'dev' && 'arn:aws:iam::699631259047:role/fsfb-arquitectura-dev-role-despliegue' ||
        github.ref_name == 'dr' && 'arn:aws:iam::699631259047:role/fsfb-arquitectura-dr-role-despliegue' }}
      branch-name: ${{ github.ref_name }}